# Generated by Django 4.2 on 2023-04-26 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_internship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='timestamp',
            new_name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='collage_name',
        ),
        migrations.AddField(
            model_name='internship',
            name='college_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
